import type { Metadata } from "next";
import { siteConfig, getSiteUrl } from "@/lib/siteConfig";
import { contentDates } from "@/lib/contentDates";
import { getPageKeywords } from "@/lib/seoKeywords";

/**
 * The build-time card generated by app/opengraph-image.tsx. Resolved against
 * `metadataBase`, so it stays correct on any host.
 */
const OG_IMAGE_PATH = "/opengraph-image";
const OG_ALT = `${siteConfig.name} — ${siteConfig.tagline}`;

interface PageMetadataOptions {
  /**
   * Page title WITHOUT the brand suffix — the root layout's title template
   * appends " | SettleinUS" automatically. Keep it under ~55 characters so the
   * rendered title stays inside Google's pixel budget.
   */
  title: string;
  description: string;
  /** Site-relative path, e.g. "/taxes/h1b". Drives the canonical URL. */
  path: string;
  /** Use "article" for editorial guides so Open Graph reports them correctly. */
  type?: "website" | "article";
  /** ISO date (YYYY-MM-DD) the page was last substantively reviewed. */
  modifiedTime?: string;
  publishedTime?: string;
  /** Opt a low-value page out of the index while keeping its links followable. */
  noindex?: boolean;
  /**
   * Search terms this page targets. Defaults to lib/seoKeywords.ts for the
   * path; pass explicitly for data-driven routes whose keywords live in
   * content JSON. Emitted as <meta name="keywords"> and, on articles, as
   * og:article:tag.
   */
  keywords?: string[];
}

export function buildPageMetadata({
  title,
  description,
  path,
  type = "website",
  modifiedTime,
  publishedTime,
  noindex = false,
  keywords,
}: PageMetadataOptions): Metadata {
  const url = getSiteUrl(path);
  const isHome = path === "/" || path === "";
  const terms = keywords ?? getPageKeywords(path);

  /*
    Article timestamps fall back to the editorial dates in lib/contentDates.ts,
    which is where the on-page "last reviewed" line and the sitemap lastmod
    already come from — so Open Graph now agrees with both. Only paths with an
    explicit entry qualify; the record's DEFAULT_DATE is deliberately not used
    here, because stamping a blog post with the site launch date is a lie.
  */
  const dates = contentDates[path];
  const published = publishedTime ?? dates?.published;
  const modified = modifiedTime ?? dates?.reviewed;

  return {
    // The root layout owns the "%s | SettleinUS" template. The homepage sets an
    // absolute title so it never renders as "SettleinUS | SettleinUS".
    title: isHome ? { absolute: title } : title,
    description,
    ...(terms.length > 0 ? { keywords: terms } : {}),
    metadataBase: new URL(getSiteUrl()),
    alternates: { canonical: url },
    robots: noindex
      ? { index: false, follow: true }
      : {
          index: true,
          follow: true,
          googleBot: {
            index: true,
            follow: true,
            "max-image-preview": "large",
            "max-snippet": -1,
            "max-video-preview": -1,
          },
        },
    openGraph: {
      title,
      description,
      url,
      siteName: siteConfig.name,
      locale: "en_US",
      type,
      ...(type === "article"
        ? {
            publishedTime: published,
            modifiedTime: modified,
            ...(terms.length > 0 ? { tags: terms } : {}),
          }
        : {}),
      // Next.js replaces (rather than deep-merges) `openGraph` per segment, so
      // a page exporting openGraph would otherwise drop the root
      // app/opengraph-image.tsx card. Pointing at that generated route keeps
      // one branded image on every page with nothing extra to maintain.
      images: [{ url: OG_IMAGE_PATH, width: 1200, height: 630, alt: OG_ALT }],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [{ url: OG_IMAGE_PATH, alt: OG_ALT }],
    },
  };
}
